"""Generate the five tutorial notebooks from per-tutorial cell specs.

The `.py` scripts are the source of truth for the tutorial code. The
notebooks wrap that code with narrative markdown and matplotlib plots.
Re-run this file after editing a tutorial to keep the notebooks in sync:

    python examples/_build_notebooks.py
"""

from __future__ import annotations

import json
from pathlib import Path


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": list(lines),
    }


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


NB01 = [
    md(
        "# Tutorial 01 — A dielectric sphere at X-band, checked against Mie\n",
        "\n",
        "A T-matrix solver for nonspherical particles must reduce to classical\n",
        "Mie theory in the `axis_ratio = 1` limit. That reduction is the\n",
        "simplest end-to-end check we can do. This tutorial builds a 1 mm\n",
        "water sphere at X-band, computes its scattering and extinction\n",
        "cross-sections via the T-matrix path, and compares against the\n",
        "closed-form Mie expressions shipped with rustmatrix.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, mie_qsca, mie_qext, scatter\n",
        "from rustmatrix.tmatrix_aux import geom_horiz_back, wl_X\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Build a sphere scatterer at X-band\n"),
    code(
        "radius_mm = 1.0\n",
        "wavelength_mm = wl_X\n",
        "m = m_w_10C[wl_X]\n",
        "\n",
        "s = Scatterer(radius=radius_mm, wavelength=wavelength_mm, m=m,\n",
        "              axis_ratio=1.0, ddelt=1e-4, ndgs=2)\n",
        "s.set_geometry(geom_horiz_back)\n",
        "S, Z = s.get_SZ()\n",
        "S\n",
    ),
    md("## Cross-sections — T-matrix vs Mie\n"),
    code(
        "size_param = 2.0 * np.pi * radius_mm / wavelength_mm\n",
        "sigma_sca_tm = scatter.sca_xsect(s, h_pol=True)\n",
        "sigma_ext_tm = scatter.ext_xsect(s, h_pol=True)\n",
        "\n",
        "geom = np.pi * radius_mm ** 2\n",
        "sigma_sca_mie = mie_qsca(size_param, m.real, m.imag) * geom\n",
        "sigma_ext_mie = mie_qext(size_param, m.real, m.imag) * geom\n",
        "\n",
        "print(f'rel err σ_sca = {abs(sigma_sca_tm-sigma_sca_mie)/sigma_sca_mie:.2e}')\n",
        "print(f'rel err σ_ext = {abs(sigma_ext_tm-sigma_ext_mie)/sigma_ext_mie:.2e}')\n",
    ),
    md("## Q_sca and Q_ext across a size-parameter sweep\n",
       "\n",
       "Plotting both curves side by side makes the Mie ripple pattern\n",
       "visible and confirms that the T-matrix follows it point-for-point.\n"),
    code(
        "xs = np.linspace(0.1, 10.0, 40)\n",
        "q_sca_mie = np.array([mie_qsca(x, m.real, m.imag) for x in xs])\n",
        "q_ext_mie = np.array([mie_qext(x, m.real, m.imag) for x in xs])\n",
        "q_sca_tm = np.empty_like(xs)\n",
        "q_ext_tm = np.empty_like(xs)\n",
        "for i, x in enumerate(xs):\n",
        "    r = x * wavelength_mm / (2.0 * np.pi)\n",
        "    si = Scatterer(radius=r, wavelength=wavelength_mm, m=m,\n",
        "                   axis_ratio=1.0, ddelt=1e-4, ndgs=2)\n",
        "    si.set_geometry(geom_horiz_back)\n",
        "    g = np.pi * r ** 2\n",
        "    q_sca_tm[i] = scatter.sca_xsect(si) / g\n",
        "    q_ext_tm[i] = scatter.ext_xsect(si) / g\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(xs, q_sca_mie, 'k-', label='Q_sca (Mie)')\n",
        "ax.plot(xs, q_ext_mie, 'k--', label='Q_ext (Mie)')\n",
        "ax.plot(xs, q_sca_tm, 'C1o', markersize=4, label='Q_sca (T-matrix)')\n",
        "ax.plot(xs, q_ext_tm, 'C2s', markersize=4, label='Q_ext (T-matrix)')\n",
        "ax.set_xlabel('size parameter  x = 2πr/λ')\n",
        "ax.set_ylabel('efficiency')\n",
        "ax.legend()\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB02 = [
    md(
        "# Tutorial 02 — A single 2 mm raindrop at C-band\n",
        "\n",
        "Falling raindrops are flattened by drag; larger drops are more\n",
        "oblate. Dual-pol radar picks this up as differential reflectivity\n",
        "Z_dr — the ratio of horizontally- to vertically-polarised\n",
        "backscattered power. This notebook computes Z_dr, Z_h, and δ_hv\n",
        "for a single drop and sweeps the axis ratio to show the\n",
        "sensitivity.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Build the drop and evaluate\n"),
    code(
        "D_mm = 2.0\n",
        "axis_ratio = 1.0 / dsr_thurai_2007(D_mm)\n",
        "s = Scatterer(radius=D_mm/2, wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "              axis_ratio=axis_ratio, Kw_sqr=K_w_sqr[wl_C],\n",
        "              ddelt=1e-4, ndgs=2)\n",
        "s.set_geometry(geom_horiz_back)\n",
        "print(f'axis ratio (h/v) = {axis_ratio:.4f}')\n",
        "print(f'Z_h = {10*np.log10(radar.refl(s, True)):.2f} dBZ')\n",
        "print(f'Z_dr = {10*np.log10(radar.Zdr(s)):+.3f} dB')\n",
        "print(f'δ_hv = {np.degrees(radar.delta_hv(s)):+.4f}°')\n",
    ),
    md("## Z_dr across the 0.5–5 mm drop-size range\n"),
    code(
        "Ds = np.linspace(0.5, 5.0, 20)\n",
        "zdrs = np.empty_like(Ds)\n",
        "for i, D in enumerate(Ds):\n",
        "    s.radius = D / 2\n",
        "    s.axis_ratio = 1.0 / dsr_thurai_2007(D)\n",
        "    zdrs[i] = 10 * np.log10(radar.Zdr(s))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(Ds, zdrs, 'C0-o')\n",
        "ax.set_xlabel('equivalent diameter D [mm]')\n",
        "ax.set_ylabel('Z_dr [dB]')\n",
        "ax.set_title('Single-drop Z_dr at C-band (Thurai 2007 shape)')\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB03 = [
    md(
        "# Tutorial 03 — Gamma-PSD rain at C-band\n",
        "\n",
        "Radar volumes sample thousands of drops. The observed Z_h, Z_dr,\n",
        "K_dp, and specific attenuation A_i are PSD-weighted integrals of\n",
        "the single-drop quantities. This notebook tabulates S(D) and Z(D)\n",
        "once, then sweeps the integrated observables across a range of\n",
        "normalised gamma PSDs parameterised by the median volume diameter\n",
        "D0.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar, psd as rs_psd\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Tabulate once, evaluate many\n"),
    code(
        "s = Scatterer(wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "              Kw_sqr=K_w_sqr[wl_C], ddelt=1e-4, ndgs=2)\n",
        "integ = rs_psd.PSDIntegrator()\n",
        "integ.D_max = 8.0\n",
        "integ.num_points = 64\n",
        "integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "s.psd_integrator = integ\n",
        "s.psd_integrator.init_scatter_table(s)\n",
    ),
    md("## Sweep median diameter D0\n"),
    code(
        "D0s = np.linspace(0.5, 3.0, 12)\n",
        "Zh = np.empty_like(D0s)\n",
        "Zdr = np.empty_like(D0s)\n",
        "Kdp = np.empty_like(D0s)\n",
        "Ai = np.empty_like(D0s)\n",
        "\n",
        "for i, D0 in enumerate(D0s):\n",
        "    s.psd = rs_psd.GammaPSD(D0=D0, Nw=8e3, mu=4)\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    Zh[i] = 10 * np.log10(radar.refl(s))\n",
        "    Zdr[i] = 10 * np.log10(radar.Zdr(s))\n",
        "    s.set_geometry(geom_horiz_forw)\n",
        "    Kdp[i] = radar.Kdp(s)\n",
        "    Ai[i] = radar.Ai(s)\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6), sharex=True)\n",
        "axes[0, 0].plot(D0s, Zh, 'C0-o'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].plot(D0s, Zdr, 'C1-o'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].plot(D0s, Kdp, 'C2-o'); axes[1, 0].set_ylabel('K_dp [°/km]')\n",
        "axes[1, 1].plot(D0s, Ai, 'C3-o'); axes[1, 1].set_ylabel('A_i [dB/km]')\n",
        "for ax in axes.flat:\n",
        "    ax.set_xlabel('D0 [mm]')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "fig.suptitle('C-band gamma-PSD rain observables (Nw=8e3, mu=4)')\n",
        "fig.tight_layout();\n",
    ),
]


NB04 = [
    md(
        "# Tutorial 04 — Oriented ice crystals at W-band\n",
        "\n",
        "Ice crystals fall with a preferred orientation and a spread of\n",
        "canting angles around it. The orientation PDF captures the spread\n",
        "and feeds directly into the dual-pol observables. This notebook\n",
        "compares the three orientation-averaging strategies rustmatrix\n",
        "ships with: none, fixed-quadrature, and adaptive.\n",
    ),
    code(
        "import time\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, orientation as rs_orient, radar\n",
        "from rustmatrix.tmatrix_aux import geom_horiz_back, wl_W\n",
        "from rustmatrix.refractive import mi\n",
    ),
    md("## One crystal, three averaging schemes\n"),
    code(
        "D_eq_mm = 0.5\n",
        "ice_m = mi(wl_W, 0.9)\n",
        "pdf = rs_orient.gaussian_pdf(std=20.0, mean=90.0)\n",
        "base = dict(radius=D_eq_mm/2, wavelength=wl_W, m=ice_m,\n",
        "            axis_ratio=0.5, ddelt=1e-4, ndgs=2)\n",
        "\n",
        "schemes = [\n",
        "    ('single', rs_orient.orient_single, {'or_pdf': pdf}),\n",
        "    ('fixed 6×12', rs_orient.orient_averaged_fixed,\n",
        "     {'or_pdf': pdf, 'n_alpha': 6, 'n_beta': 12}),\n",
        "    ('adaptive', rs_orient.orient_averaged_adaptive, {'or_pdf': pdf}),\n",
        "]\n",
        "rows = []\n",
        "for name, orient, extra in schemes:\n",
        "    s = Scatterer(**base, **extra)\n",
        "    s.orient = orient\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    t0 = time.perf_counter()\n",
        "    zdr = radar.Zdr(s)\n",
        "    elapsed = time.perf_counter() - t0\n",
        "    rows.append((name, 10*np.log10(zdr), elapsed))\n",
        "    print(f'{name:<12} Z_dr = {10*np.log10(zdr):+.4f} dB   ({elapsed*1000:.1f} ms)')\n",
    ),
    md("## Canting-angle spread sensitivity\n",
       "\n",
       "Sweep the Gaussian PDF's `std` parameter to see how rapidly Z_dr\n",
       "collapses as the orientation spread widens.\n"),
    code(
        "stds = np.array([1, 5, 10, 15, 20, 30, 45, 60])\n",
        "zdrs = np.empty_like(stds, dtype=float)\n",
        "for i, sd in enumerate(stds):\n",
        "    s = Scatterer(**base)\n",
        "    s.orient = rs_orient.orient_averaged_fixed\n",
        "    s.or_pdf = rs_orient.gaussian_pdf(std=float(sd), mean=90.0)\n",
        "    s.n_alpha, s.n_beta = 6, 12\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    zdrs[i] = 10 * np.log10(radar.Zdr(s))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(stds, zdrs, 'C0-o')\n",
        "ax.set_xlabel('canting-angle σ [deg]')\n",
        "ax.set_ylabel('Z_dr [dB]')\n",
        "ax.set_title('W-band prolate ice column, oriented')\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB05 = [
    md(
        "# Tutorial 05 — One PSD, six radar bands\n",
        "\n",
        "Retrieval algorithms that use more than one frequency need a\n",
        "forward model that works across the whole instrument suite. This\n",
        "notebook runs the same moderate-convective gamma PSD through\n",
        "rustmatrix at S, C, X, Ku, Ka, and W band and plots the frequency\n",
        "response of the dual-pol observables.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar, psd as rs_psd\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr,\n",
        "                                      wl_S, wl_C, wl_X, wl_Ku,\n",
        "                                      wl_Ka, wl_W)\n",
        "from rustmatrix.refractive import m_w_20C\n",
        "\n",
        "BANDS = [('S', wl_S), ('C', wl_C), ('X', wl_X),\n",
        "         ('Ku', wl_Ku), ('Ka', wl_Ka), ('W', wl_W)]\n",
    ),
    md("## Run the six bands\n"),
    code(
        "def run(wl):\n",
        "    s = Scatterer(wavelength=wl, m=m_w_20C[wl],\n",
        "                  Kw_sqr=K_w_sqr[wl], ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 8.0\n",
        "    integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = rs_psd.GammaPSD(D0=1.5, Nw=8e3, mu=4)\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    Zh = 10 * np.log10(radar.refl(s))\n",
        "    Zdr = 10 * np.log10(radar.Zdr(s))\n",
        "    s.set_geometry(geom_horiz_forw)\n",
        "    return Zh, Zdr, radar.Kdp(s), radar.Ai(s)\n",
        "\n",
        "Zh = {}; Zdr = {}; Kdp = {}; Ai = {}\n",
        "for name, wl in BANDS:\n",
        "    Zh[name], Zdr[name], Kdp[name], Ai[name] = run(wl)\n",
        "    print(f'{name:<3} Z_h={Zh[name]:6.2f}  Z_dr={Zdr[name]:+.3f}  '\n",
        "          f'K_dp={Kdp[name]:+.3f}  A_i={Ai[name]:.4f}')\n",
    ),
    md("## Plot the frequency response\n"),
    code(
        "names = [b[0] for b in BANDS]\n",
        "wls = np.array([b[1] for b in BANDS])\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6))\n",
        "axes[0, 0].semilogx(wls, [Zh[n] for n in names], 'o-'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].semilogx(wls, [Zdr[n] for n in names], 'o-'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].semilogx(wls, [Kdp[n] for n in names], 'o-'); axes[1, 0].set_ylabel('K_dp [°/km]')\n",
        "axes[1, 1].semilogx(wls, [Ai[n] for n in names], 'o-'); axes[1, 1].set_ylabel('A_i [dB/km]')\n",
        "for ax, label in zip(axes.flat, names*4):\n",
        "    ax.set_xlabel('wavelength [mm]')\n",
        "    ax.grid(True, alpha=0.3, which='both')\n",
        "    for name, wl in BANDS:\n",
        "        ax.axvline(wl, color='k', alpha=0.1)\n",
        "fig.suptitle('Moderate convective rain (D0=1.5 mm): frequency response')\n",
        "fig.tight_layout();\n",
    ),
]


NB06 = [
    md(
        "# Tutorial 06 — Hydrometeor mixtures at C-band\n",
        "\n",
        "Real radar volumes sometimes contain more than a single species —\n",
        "rain with melting ice, pristine crystals with aggregates, graupel\n",
        "in the mixed phase. The combined polarimetric signature is the\n",
        "incoherent sum of the per-species S and Z matrices; the\n",
        "*non*-linear observables (Z_dr, ρ_hv, δ_hv) cannot be averaged\n",
        "from per-species values and must be computed from the mixture's\n",
        "summed amplitude and phase matrices.\n",
        "\n",
        "`HydroMix` takes a list of `MixtureComponent(Scatterer, PSD)` pairs\n",
        "and exposes a Scatterer-shaped API so the usual `radar.*` helpers\n",
        "work on it directly.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import (HydroMix, MixtureComponent,\n",
        "                         Scatterer, radar, psd as rs_psd)\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C, mi\n",
    ),
    md("## Build one scatterer per species\n",
       "\n",
       "Each species gets its own `PSDIntegrator` that tabulates S(D)\n",
       "and Z(D) for whatever refractive index, axis ratio, and orientation\n",
       "PDF the species requires. All integrators must register the same\n",
       "geometries the mixture will query and must share the wavelength.\n"),
    code(
        "def build_rain():\n",
        "    s = Scatterer(wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "                  Kw_sqr=K_w_sqr[wl_C], ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 6.0; integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    return s\n",
        "\n",
        "def build_ice():\n",
        "    s = Scatterer(wavelength=wl_C, m=mi(wl_C, 0.2),\n",
        "                  Kw_sqr=K_w_sqr[wl_C], axis_ratio=0.6,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 8.0; integ.num_points = 64\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    return s\n",
        "\n",
        "rain = build_rain(); ice = build_ice()\n",
        "rain_psd = rs_psd.GammaPSD(D0=1.5, Nw=8e3, mu=4, D_max=6.0)\n",
        "ice_psd  = rs_psd.ExponentialPSD(N0=5e3, Lambda=2.0, D_max=8.0)\n",
        "rain.psd = rain_psd; ice.psd = ice_psd\n",
    ),
    md("## Assemble the mixture and read the observables\n"),
    code(
        "mix = HydroMix([\n",
        "    MixtureComponent(rain, rain_psd, 'rain'),\n",
        "    MixtureComponent(ice,  ice_psd,  'ice'),\n",
        "])\n",
        "\n",
        "def obs(x):\n",
        "    x.set_geometry(geom_horiz_back)\n",
        "    out = dict(Zh=10*np.log10(radar.refl(x)),\n",
        "               Zdr=10*np.log10(radar.Zdr(x)),\n",
        "               rho=radar.rho_hv(x))\n",
        "    x.set_geometry(geom_horiz_forw)\n",
        "    out['Kdp'] = radar.Kdp(x); out['Ai'] = radar.Ai(x)\n",
        "    return out\n",
        "\n",
        "for name, obj in [('rain only', rain),\n",
        "                  ('ice only',  ice),\n",
        "                  ('mixture',   mix)]:\n",
        "    o = obs(obj)\n",
        "    print(f'{name:<12} Z_h={o[\"Zh\"]:6.2f}  Z_dr={o[\"Zdr\"]:+.3f}  '\n",
        "          f'ρ_hv={o[\"rho\"]:.5f}  K_dp={o[\"Kdp\"]:+.3f}  A_i={o[\"Ai\"]:.4f}')\n",
    ),
    md("## Sweep the ice fraction\n",
       "\n",
       "Scale the ice PSD's N0 from zero up to the rain contribution and\n",
       "watch Z_dr, ρ_hv, and K_dp interpolate between the rain-only and\n",
       "ice-heavy limits. Because both S and Z are linear in N(D), this\n",
       "is exactly the behaviour predicted by incoherent mixing.\n"),
    code(
        "N0_ice_sweep = np.linspace(0.0, 2e4, 9)\n",
        "Zh_sw, Zdr_sw, rho_sw, Kdp_sw = [], [], [], []\n",
        "for N0 in N0_ice_sweep:\n",
        "    ice_psd_sw = rs_psd.ExponentialPSD(N0=float(N0), Lambda=2.0, D_max=8.0)\n",
        "    m_sw = HydroMix([\n",
        "        MixtureComponent(rain, rain_psd, 'rain'),\n",
        "        MixtureComponent(ice,  ice_psd_sw, 'ice'),\n",
        "    ])\n",
        "    o = obs(m_sw)\n",
        "    Zh_sw.append(o['Zh']); Zdr_sw.append(o['Zdr'])\n",
        "    rho_sw.append(o['rho']); Kdp_sw.append(o['Kdp'])\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6), sharex=True)\n",
        "axes[0, 0].plot(N0_ice_sweep, Zh_sw,  'C0-o'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].plot(N0_ice_sweep, Zdr_sw, 'C1-o'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].plot(N0_ice_sweep, rho_sw, 'C2-o'); axes[1, 0].set_ylabel('ρ_hv')\n",
        "axes[1, 1].plot(N0_ice_sweep, Kdp_sw, 'C3-o'); axes[1, 1].set_ylabel('K_dp [°/km]')\n",
        "for ax in axes.flat:\n",
        "    ax.set_xlabel('ice N₀ [m⁻³ mm⁻¹]')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "fig.suptitle('C-band rain + oriented ice — sweeping the ice concentration')\n",
        "fig.tight_layout();\n",
    ),
]


NB07 = [
    md(
        "# Tutorial 07 — W-band Mie Doppler spectrum in convective rain (Kollias 2002)\n",
        "\n",
        "Reference: Kollias, P., Albrecht, B. A., and Marks Jr., F. D., 2002.\n",
        "*Cloud radar observations of vertical drafts and microphysics in\n",
        "convective rain*, J. Geophys. Res., 107 (doi:10.1029/2001JD002033).\n",
        "\n",
        "At 94 GHz the raindrop backscattering cross-section σ_b(D) is no\n",
        "longer Rayleigh — it rings through a sequence of Mie maxima and\n",
        "minima. Because each drop falls at a deterministic terminal velocity\n",
        "v_t(D), these Mie features map directly onto the observed Doppler\n",
        "spectrum: the first Mie minimum appears at v ≈ 5.9 m/s in still air,\n",
        "and any displacement of that feature from its theoretical location\n",
        "is a direct measurement of the mean vertical air motion — independent\n",
        "of the drop-size distribution. This notebook reproduces the paper's\n",
        "Figures 1–3 and demonstrates the air-motion retrieval.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, SpectralIntegrator, radar, spectra\n",
        "from rustmatrix.psd import ExponentialPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_20C\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, dsr_thurai_2007,\n",
        "                                      geom_vert_back, wl_W)\n",
    ),
    md("## Figure 1 — single-drop σ_b(D) at 94 GHz\n",
       "\n",
       "Each drop's backscatter cross-section at vertical incidence, as a\n",
       "function of its equivalent diameter D. The Rayleigh D⁶ regime holds\n",
       "only below about 0.7 mm; beyond that the curve oscillates through\n",
       "distinct Mie resonances.\n"),
    code(
        "def build_drop(D_mm, oblate=True):\n",
        "    axis_ratio = 1.0 / dsr_thurai_2007(D_mm) if oblate else 1.0\n",
        "    s = Scatterer(radius=D_mm/2, wavelength=wl_W, m=m_w_20C[wl_W],\n",
        "                  Kw_sqr=K_w_sqr[wl_W], axis_ratio=axis_ratio,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return s\n",
        "\n",
        "D_grid = np.linspace(0.05, 5.0, 400)    # mm\n",
        "sigma_b_obl = np.array([radar.radar_xsect(build_drop(D, True))\n",
        "                        for D in D_grid])\n",
        "sigma_b_sph = np.array([radar.radar_xsect(build_drop(D, False))\n",
        "                        for D in D_grid])\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.semilogy(D_grid, sigma_b_obl, 'C0-', label='oblate (Thurai 2007)')\n",
        "ax.semilogy(D_grid, sigma_b_sph, 'k--', label='sphere')\n",
        "ax.set_xlabel('diameter D [mm]')\n",
        "ax.set_ylabel(r'$\\sigma_b$ [mm²]')\n",
        "ax.set_title('Figure 1 — single-drop backscatter at 94 GHz, vertical incidence')\n",
        "ax.legend(); ax.grid(True, which='both', alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Figure 3 — Mie oscillations mapped to terminal velocity\n",
       "\n",
       "Plotting σ_b / (π r²) versus the drop's terminal fall speed collapses\n",
       "the Mie ripple structure into the velocity coordinate the radar\n",
       "actually measures. Oblate drops fall slightly faster than the spheres\n",
       "of the same equivalent diameter, so their first Mie minimum lands at\n",
       "v ≈ 5.95 m/s instead of 5.88 m/s — a 7 cm/s shift that matters when\n",
       "you're using it as a zero-air-motion fiducial.\n"),
    code(
        "fall = spectra.fall_speed.atlas_srivastava_sekhon_1973\n",
        "v_t = fall(D_grid)\n",
        "r_mm = D_grid / 2.0\n",
        "norm = np.pi * r_mm ** 2\n",
        "\n",
        "def first_min(D, sigma_b):\n",
        "    mask = (D > 1.3) & (D < 2.2)\n",
        "    i = np.argmin(sigma_b[mask])\n",
        "    return D[mask][i], v_t[mask][i]\n",
        "\n",
        "D_min_obl, v_min_obl = first_min(D_grid, sigma_b_obl)\n",
        "D_min_sph, v_min_sph = first_min(D_grid, sigma_b_sph)\n",
        "print(f'First Mie minimum, oblate: D = {D_min_obl:.3f} mm, '\n",
        "      f'v = {v_min_obl:.3f} m/s')\n",
        "print(f'First Mie minimum, sphere: D = {D_min_sph:.3f} mm, '\n",
        "      f'v = {v_min_sph:.3f} m/s')\n",
        "print(f'Shift: {100 * (v_min_obl - v_min_sph):+.1f} cm/s '\n",
        "       '(oblate vs sphere)')\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.semilogy(v_t, sigma_b_obl / norm, 'C0-', label='oblate spheroids')\n",
        "ax.semilogy(v_t, sigma_b_sph / norm, 'k--', label='spheres')\n",
        "ax.axvline(v_min_obl, color='C3', alpha=0.6,\n",
        "           label=f'oblate 1st min: {v_min_obl:.2f} m/s')\n",
        "ax.axvline(v_min_sph, color='C2', alpha=0.6, ls=':',\n",
        "           label=f'sphere 1st min: {v_min_sph:.2f} m/s')\n",
        "ax.set_xlim(0, 10); ax.set_ylim(1e-5, 1e1)\n",
        "ax.set_xlabel('terminal velocity $v_t(D)$ [m/s]')\n",
        "ax.set_ylabel(r'$\\sigma_b / (\\pi r^2)$')\n",
        "ax.set_title('Figure 3 — Mie ripples in velocity space (94 GHz)')\n",
        "ax.legend(); ax.grid(True, which='both', alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Full Doppler spectrum at 94 GHz (cf. Figure 2)\n",
       "\n",
       "Running an exponential rain DSD through `SpectralIntegrator` yields\n",
       "the Mie-modulated Doppler spectrum the paper observes. With enough\n",
       "PSD diameter samples, the Mie minima appear as *notches* in sZ_h(v)\n",
       "at the velocities we just identified.\n",
       "\n",
       "### Note on diameter sampling\n",
       "With zero turbulence and too few PSD diameters, the spectrum\n",
       "*looks* spiky — every tabulated drop lands in a single velocity bin\n",
       "and the bins between stay at zero. This is a sampling artifact,\n",
       "**not** a physical feature: densify the diameter grid (bump\n",
       "`num_points` from 64 to 256) or add a hair of turbulence and the\n",
       "spikes collapse into the smooth Mie-modulated spectrum.\n"),
    code(
        "def build_rain_W(num_points=256):\n",
        "    s = Scatterer(wavelength=wl_W, m=m_w_20C[wl_W],\n",
        "                  Kw_sqr=K_w_sqr[wl_W], ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = 5.0\n",
        "    integ.num_points = num_points\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=8e3, Lambda=2.2, D_max=5.0)\n",
        "    return s\n",
        "\n",
        "rain64  = build_rain_W(num_points=64)\n",
        "rain256 = build_rain_W(num_points=256)\n",
        "\n",
        "def run(sc, turb, w=0.0):\n",
        "    return SpectralIntegrator(\n",
        "        sc, fall_speed=fall, turbulence=turb, w=w,\n",
        "        v_min=-1.0, v_max=12.0, n_bins=1024,\n",
        "        geometry_backscatter=geom_vert_back,\n",
        "    ).run()\n",
        "\n",
        "r_sparse = run(rain64,  spectra.NoTurbulence())\n",
        "r_dense  = run(rain256, spectra.NoTurbulence())\n",
        "r_turb   = run(rain256, spectra.GaussianTurbulence(0.1))\n",
        "\n",
        "def dBZ(x):\n",
        "    return 10 * np.log10(np.maximum(x, 1e-10))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.plot(r_sparse.v, dBZ(r_sparse.sZ_h), 'C1-', alpha=0.6,\n",
        "        label='num_points=64, no turb (spiky — sampling artifact)')\n",
        "ax.plot(r_dense.v,  dBZ(r_dense.sZ_h),  'C0-',\n",
        "        label='num_points=256, no turb (Mie notches resolved)')\n",
        "ax.plot(r_turb.v,   dBZ(r_turb.sZ_h),   'C3-', alpha=0.8,\n",
        "        label='num_points=256, σ_t=0.1 m/s')\n",
        "ax.axvline(v_min_obl, color='k', ls=':', alpha=0.6,\n",
        "           label=f'1st Mie min ({v_min_obl:.2f} m/s)')\n",
        "ax.set_xlim(0, 10); ax.set_ylim(-50, 25)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax.set_title('W-band Doppler spectrum — Mie notches and sampling artifact')\n",
        "ax.legend(fontsize=9); ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Air-motion retrieval\n",
       "\n",
       "Simulate a 1 m/s downward air motion (positive *w* under our\n",
       "convention): the whole spectrum shifts by *w*, so the first Mie\n",
       "minimum moves from 5.95 m/s to ~6.95 m/s. Subtracting the theoretical\n",
       "still-air Mie-minimum location from the observed one recovers the air\n",
       "motion — this is the Kollias 2002 technique in a nutshell, and it\n",
       "doesn't depend on knowing the DSD.\n"),
    code(
        "r_w = run(rain256, spectra.GaussianTurbulence(0.1), w=1.0)\n",
        "\n",
        "band = (r_w.v > v_min_obl) & (r_w.v < v_min_obl + 2.5)\n",
        "v_obs = r_w.v[band][int(np.argmin(r_w.sZ_h[band]))]\n",
        "w_retrieved = v_obs - v_min_obl\n",
        "print(f'Prescribed air motion  w = +1.00 m/s (downward)')\n",
        "print(f'Observed 1st Mie min   v = {v_obs:.2f} m/s')\n",
        "print(f'Still-air 1st Mie min  v = {v_min_obl:.2f} m/s')\n",
        "print(f'Retrieved w            = {w_retrieved:+.2f} m/s')\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.plot(r_turb.v, dBZ(r_turb.sZ_h), 'C0-', label='w = 0')\n",
        "ax.plot(r_w.v,    dBZ(r_w.sZ_h),    'C3-', label='w = +1 m/s')\n",
        "ax.axvline(v_min_obl, color='k',  ls=':', alpha=0.6,\n",
        "           label=f'still-air min ({v_min_obl:.2f})')\n",
        "ax.axvline(v_obs,     color='C3', ls=':', alpha=0.6,\n",
        "           label=f'shifted min ({v_obs:.2f})')\n",
        "ax.set_xlim(0, 10); ax.set_ylim(-50, 25)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax.set_title('Kollias 2002 air-motion retrieval: Mie minimum as a fiducial')\n",
        "ax.legend(fontsize=9); ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB08 = [
    md(
        "# Tutorial 08 — Dual-frequency non-Rayleigh snowfall spectra (Billault-Roux 2023)\n",
        "\n",
        "Reference: Billault-Roux, A.-C., Ghiggi, G., Jaffeux, L., Martini, A.,\n",
        "Viltard, N., and Berne, A., 2023. *Dual-frequency spectral radar\n",
        "retrieval of snowfall microphysics: a physics-driven deep-learning\n",
        "approach*, Atmos. Meas. Tech., 16, 911–931\n",
        "(doi:10.5194/amt-16-911-2023).\n",
        "\n",
        "The paper relies on a simple but powerful asymmetry: at cloud-radar\n",
        "frequencies small, slow-falling snow particles are still Rayleigh, so\n",
        "their X-band and W-band reflectivities agree — but the large,\n",
        "fast-falling ones are non-Rayleigh at W-band, so their W-band\n",
        "spectral reflectivity is *smaller* than X-band. The **spectral\n",
        "dual-wavelength ratio** sDWR(v) = 10·log₁₀(sZ_X / sZ_W) stays near 0\n",
        "at low velocities and rises to several dB at high velocities — a\n",
        "direct fingerprint of the large-particle size distribution tail,\n",
        "untangled from turbulence and wind offsets.\n",
        "\n",
        "This notebook reproduces that signature by running the same snow\n",
        "scatterer, PSD, fall-speed, and turbulence through\n",
        "`SpectralIntegrator` at X-band (9.5 GHz) and W-band (94 GHz).\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, SpectralIntegrator, radar, spectra\n",
        "from rustmatrix.psd import ExponentialPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import mi\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, geom_vert_back,\n",
        "                                      wl_X, wl_W)\n",
    ),
    md("## Build matched snow scatterers at X-band and W-band\n",
       "\n",
       "Both scatterers share the same oblate low-density aggregate habit,\n",
       "PSD, and velocity grid. The *only* change across the two runs is the\n",
       "radar wavelength.\n",
       "\n",
       "PSD and habit parameters are grounded in the ICE-GENESIS 23 January\n",
       "2021 case of Billault-Roux et al. 2023 (Fig. 5 snowfall layer):\n",
       "\n",
       "* oblate aggregates, ρ_ice = 0.1 g/cm³ (low-density, typical of\n",
       "  mixed-habit aggregates), axis ratio 0.6, D_max = 5 mm\n",
       "* exponential PSD, N₀ = 2×10⁴ m⁻³ mm⁻¹, Λ = 2.5 mm⁻¹\n",
       "* median-volume diameter D₀ = 3.67/Λ ≈ 1.5 mm\n",
       "* IWC = (π ρ_ice / Λ⁴) · N₀ ≈ 0.16 g/m³ — a moderate aggregation\n",
       "  layer, well within the synthetic training range the authors drew\n",
       "  from their MASCDB disdrometer database.\n",
       "\n",
       "These numbers land bulk Z_h(X) around 17 dBZ (moderate snowfall,\n",
       "consistent with the paper's Fig. 5 observations at ~15:10 UTC) and a\n",
       "non-Rayleigh-driven bulk DWR on the order of 15–20 dB — *not* the\n",
       "50 dBZ / 25 dB outlier you get if you blindly pick Λ = 0.8 mm⁻¹ and\n",
       "D_max = 10 mm (D₀ ≈ 5 mm, IWC > 10 g/m³ — a reflectivity-saturating\n",
       "deep convective snow cell, not an aggregation layer).\n"),
    code(
        "RHO_ICE = 0.1\n",
        "AXIS_RATIO = 0.6\n",
        "D_MAX = 5.0\n",
        "N0 = 2e4\n",
        "LAMBDA = 2.5\n",
        "\n",
        "def build_snow(wl):\n",
        "    s = Scatterer(wavelength=wl, m=mi(wl, RHO_ICE),\n",
        "                  Kw_sqr=K_w_sqr[wl], axis_ratio=AXIS_RATIO,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = D_MAX\n",
        "    integ.num_points = 256\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=N0, Lambda=LAMBDA, D_max=D_MAX)\n",
        "    return s\n",
        "\n",
        "snow_X = build_snow(wl_X)\n",
        "snow_W = build_snow(wl_W)\n",
    ),
    md("## σ_b(D) at X-band vs W-band — the non-Rayleigh onset\n",
       "\n",
       "Up to about 2 mm equivalent diameter the two σ_b(D) curves are\n",
       "essentially parallel D⁶ power laws (Rayleigh). Above ~3 mm the\n",
       "W-band curve rolls over and develops Mie structure while the X-band\n",
       "curve keeps rising — this is the imprint the dual-frequency spectrum\n",
       "will show up as a velocity-resolved sDWR.\n"),
    code(
        "def sigma_b(wl, D_mm):\n",
        "    s = Scatterer(radius=D_mm/2, wavelength=wl,\n",
        "                  m=mi(wl, RHO_ICE), Kw_sqr=K_w_sqr[wl],\n",
        "                  axis_ratio=AXIS_RATIO, ddelt=1e-4, ndgs=2)\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return radar.radar_xsect(s)\n",
        "\n",
        "D = np.linspace(0.1, D_MAX, 150)\n",
        "sb_X = np.array([sigma_b(wl_X, d) for d in D])\n",
        "sb_W = np.array([sigma_b(wl_W, d) for d in D])\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.loglog(D, sb_X, 'C0-', label='X-band (9 GHz)')\n",
        "ax.loglog(D, sb_W, 'C3-', label='W-band (94 GHz)')\n",
        "ax.set_xlabel('equivalent diameter D [mm]')\n",
        "ax.set_ylabel(r'$\\sigma_b$ [mm²]')\n",
        "ax.set_title('Snow backscatter at vertical incidence')\n",
        "ax.legend(); ax.grid(True, which='both', alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Dual-frequency Doppler spectra\n",
       "\n",
       "Same fall-speed model (Locatelli–Hobbs aggregates), same turbulence,\n",
       "same velocity grid — only the radar wavelength changes.\n"),
    code(
        "fall = spectra.fall_speed.locatelli_hobbs_1974_aggregates\n",
        "turb = spectra.GaussianTurbulence(0.2)\n",
        "V_MIN, V_MAX = -2.0, 4.0\n",
        "N_BINS = 1024\n",
        "\n",
        "def run(sc):\n",
        "    return SpectralIntegrator(\n",
        "        sc, fall_speed=fall, turbulence=turb,\n",
        "        v_min=V_MIN, v_max=V_MAX, n_bins=N_BINS,\n",
        "        geometry_backscatter=geom_vert_back,\n",
        "    ).run()\n",
        "\n",
        "r_X = run(snow_X)\n",
        "r_W = run(snow_W)\n",
        "\n",
        "def dBZ(x):\n",
        "    return 10 * np.log10(np.maximum(x, 1e-12))\n",
        "\n",
        "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6), sharex=True)\n",
        "ax1.plot(r_X.v, dBZ(r_X.sZ_h), 'C0-', label='X-band')\n",
        "ax1.plot(r_W.v, dBZ(r_W.sZ_h), 'C3-', label='W-band')\n",
        "ax1.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax1.set_title('Dual-frequency spectra of snowfall — vertical pointing')\n",
        "ax1.legend(); ax1.grid(True, alpha=0.3)\n",
        "\n",
        "sDWR = dBZ(r_X.sZ_h) - dBZ(r_W.sZ_h)\n",
        "good = (r_X.sZ_h > 1e-8) & (r_W.sZ_h > 1e-10)\n",
        "ax2.plot(r_X.v[good], sDWR[good], 'C2-')\n",
        "ax2.axhline(0.0, color='k', ls=':', alpha=0.6)\n",
        "ax2.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax2.set_ylabel('sDWR$_{X-W}$ [dB]')\n",
        "ax2.set_title('Spectral dual-wavelength ratio: Rayleigh at low v, '\n",
        "              'non-Rayleigh at high v')\n",
        "ax2.grid(True, alpha=0.3)\n",
        "ax2.set_xlim(V_MIN, V_MAX)\n",
        "fig.tight_layout();\n",
    ),
    md("## Reading the signature\n",
       "\n",
       "At velocities below ~0.5 m/s (small aggregates, well inside the\n",
       "Rayleigh regime at both bands) sDWR is essentially zero. It rises\n",
       "monotonically with v as the fastest-falling particles move into the\n",
       "W-band non-Rayleigh regime while remaining Rayleigh at X-band. The\n",
       "magnitude of the rise at a given velocity is a direct proxy for the\n",
       "*size* of the drops there — which is exactly the lever Billault-Roux\n",
       "et al. 2023 use to retrieve the PSD tail, with deep learning\n",
       "shouldering the joint dependence on turbulence and shape.\n"),
    code(
        "print(f'bulk Z_h (X-band) = '\n",
        "      f'{10*np.log10(np.trapezoid(r_X.sZ_h, r_X.v)):.2f} dBZ')\n",
        "print(f'bulk Z_h (W-band) = '\n",
        "      f'{10*np.log10(np.trapezoid(r_W.sZ_h, r_W.v)):.2f} dBZ')\n",
        "print(f'bulk DWR          = '\n",
        "      f'{10*np.log10(np.trapezoid(r_X.sZ_h, r_X.v) / np.trapezoid(r_W.sZ_h, r_W.v)):.2f} dB')\n",
        "print()\n",
        "v_samples = [0.3, 0.5, 0.8, 1.0, 1.3, 1.6]\n",
        "print('sDWR(v) at selected velocities:')\n",
        "for vs in v_samples:\n",
        "    i = int(np.argmin(np.abs(r_X.v - vs)))\n",
        "    print(f'  v = {r_X.v[i]:.2f} m/s   sDWR = '\n",
        "          f'{dBZ(r_X.sZ_h[i]) - dBZ(r_W.sZ_h[i]):+.2f} dB')\n",
    ),
]


NB09 = [
    md(
        "# Tutorial 09 — Reproducing Zhu, Kollias, Yang (2023): particle-inertia spectra\n",
        "\n",
        "Reference: Zhu, Z., Kollias, P., and Yang, F., 2023. *Particle Inertia\n",
        "Effects on Radar Doppler Spectra Simulation*, Atmos. Meas. Tech.\n",
        "Discuss. MATLAB simulator source: https://zenodo.org/records/7897981\n",
        "\n",
        "The conventional way to get a turbulent radar Doppler spectrum from a\n",
        "drop-size distribution is to convolve the drop reflectivity spectrum\n",
        "with a single Gaussian of width σ_air. Zhu 2023 argues — and shows\n",
        "with a per-drop drag-ODE simulator — that this is wrong: small drops\n",
        "are passive tracers, but large drops are ballistic and under-respond\n",
        "to the small-scale eddies of the wind field. The broadening kernel is\n",
        "*diameter-dependent*, σ_t(D), and narrows toward the large-drop end.\n",
        "\n",
        "rustmatrix ships an analytical Stokes-number low-pass response,\n",
        "`InertialZeng2023`, implementing this physics family (the Zeng et al.\n",
        "2023 companion paper):\n",
        "\n",
        "$$\\sigma_t(D) = \\frac{\\sigma_{\\rm air}}{\\sqrt{1 + \\mathrm{St}(D)^2}}, \\qquad \\mathrm{St} = \\tau_p(D) / \\tau_{\\rm eddy}.$$\n",
        "\n",
        "This notebook reproduces Zhu 2023's configuration — W-band, ±12 m/s\n",
        "Nyquist, 1024 bins, SNR = 40 dB, exponential warm-rain PSD — and\n",
        "compares conventional Gaussian broadening to the inertia-aware kernel.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, SpectralIntegrator, spectra\n",
        "from rustmatrix.psd import ExponentialPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_10C\n",
        "from rustmatrix.tmatrix_aux import K_w_sqr, geom_vert_back, wl_W\n",
        "\n",
        "# --- Zhu 2023 configuration ---\n",
        "V_MIN, V_MAX = -12.0, 12.0\n",
        "NFFT = 1024\n",
        "SNR_DB = 40.0\n",
        "Z_DBZ = 20.0\n",
        "SIGMA_AIR = 0.289        # std of uniform [-0.5, 0.5] wind field\n",
        "EPSILON = 1e-2           # dissipation rate (m²/s³)\n",
        "L_O = 0.1                # integral length scale (m)\n",
    ),
    md("## Build the W-band rain scatterer and PSD\n",
       "\n",
       "Zhu 2023's MATLAB code uses N(D) = N₀·exp(shape·D_cm)·1e4 m⁻³ µm⁻¹\n",
       "with N₀ = 0.08 and shape = -20. In rustmatrix's mm-based units this\n",
       "is N(D_mm) = 8×10⁵ · exp(-2·D_mm) m⁻³ mm⁻¹, truncated at D_max=4 mm.\n"),
    code(
        "s = Scatterer(wavelength=wl_W, m=m_w_10C[wl_W],\n",
        "              Kw_sqr=K_w_sqr[wl_W], ddelt=1e-4, ndgs=2)\n",
        "integ = PSDIntegrator()\n",
        "integ.D_max = 4.0; integ.num_points = 128\n",
        "integ.geometries = (geom_vert_back,)\n",
        "s.psd_integrator = integ\n",
        "s.psd_integrator.init_scatter_table(s)\n",
        "s.psd = ExponentialPSD(N0=8e5, Lambda=2.0, D_max=4.0)\n",
    ),
    md("## The inertial reduction factor σ_t(D) / σ_air\n",
       "\n",
       "At fixed σ_air and ε, the reduction factor depends only on D through\n",
       "the particle relaxation time τ_p(D) = v_t(D)/g. This plot is the\n",
       "physical crux of Zhu 2023 — large drops experience less-effective\n",
       "turbulence broadening than small drops.\n"),
    code(
        "zeng = spectra.InertialZeng2023(sigma_air=SIGMA_AIR,\n",
        "                                 epsilon=EPSILON, L_o=L_O)\n",
        "D_plot = np.linspace(0.1, 4.0, 200)\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(D_plot, zeng(D_plot) / SIGMA_AIR, 'C0-', lw=2)\n",
        "ax.axhline(1.0, color='k', ls='--', alpha=0.5,\n",
        "           label='conventional: σ_t / σ_air = 1')\n",
        "ax.set_xlabel('drop diameter D [mm]')\n",
        "ax.set_ylabel('σ_t(D) / σ_air')\n",
        "ax.set_title(f'Inertial reduction (σ_air={SIGMA_AIR}, '\n",
        "             f'ε={EPSILON}, L_o={L_O})')\n",
        "ax.legend(); ax.grid(True, alpha=0.3)\n",
        "ax.set_ylim(0.0, 1.05)\n",
        "fig.tight_layout();\n",
    ),
    md("## Run two spectra: conventional vs. inertia-aware\n",
       "\n",
       "Both use the same fall-speed model, velocity grid, and noise floor.\n",
       "The only difference is the turbulence kernel — constant σ_air vs.\n",
       "σ_t(D) from Zeng 2023.\n"),
    code(
        "# Receiver noise: SNR = 40 dB over 20 dBZ reference.\n",
        "noise = 10 ** (Z_DBZ / 10.0) / 10 ** (SNR_DB / 10.0)\n",
        "\n",
        "common = dict(\n",
        "    fall_speed=spectra.fall_speed.atlas_srivastava_sekhon_1973,\n",
        "    v_min=V_MIN, v_max=V_MAX, n_bins=NFFT,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        "    noise=noise,\n",
        ")\n",
        "\n",
        "conv = SpectralIntegrator(s,\n",
        "    turbulence=spectra.GaussianTurbulence(SIGMA_AIR),\n",
        "    **common,\n",
        ").run()\n",
        "\n",
        "iner = SpectralIntegrator(s,\n",
        "    turbulence=spectra.InertialZeng2023(\n",
        "        sigma_air=SIGMA_AIR, epsilon=EPSILON, L_o=L_O),\n",
        "    **common,\n",
        ").run()\n",
        "\n",
        "print(f'Conventional integrated Z_h = '\n",
        "      f'{10*np.log10(np.trapezoid(conv.sZ_h, conv.v)):.2f} dBZ')\n",
        "print(f'Inertia-aware integrated Z_h = '\n",
        "      f'{10*np.log10(np.trapezoid(iner.sZ_h, iner.v)):.2f} dBZ')\n",
        "print(f'Noise floor              = '\n",
        "      f'{noise:.4f} mm⁶/m³ ('\n",
        "      f'{10*np.log10(noise / (V_MAX - V_MIN)):.2f} '\n",
        "      f'dBZ / (m/s))')\n",
    ),
    md("## Spectrum comparison in dBZ\n",
       "\n",
       "On a log scale the inertia correction visibly narrows the spectrum\n",
       "near the fall-speed of the largest drops (the right-hand tail). The\n",
       "total power integrates to the same reflectivity — this is a\n",
       "redistribution of spectral shape, not a gain change.\n"),
    code(
        "def dBZ(x):\n",
        "    return 10 * np.log10(np.maximum(x, 1e-12))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.plot(conv.v, dBZ(conv.sZ_h), 'C0-',\n",
        "        label='conventional Gaussian')\n",
        "ax.plot(iner.v, dBZ(iner.sZ_h), 'C3-',\n",
        "        label='inertia-aware (Zeng 2023)')\n",
        "ax.axhline(dBZ(noise / (V_MAX - V_MIN)), color='k',\n",
        "           ls='--', alpha=0.5, label='noise floor')\n",
        "peak = max(dBZ(conv.sZ_h).max(), dBZ(iner.sZ_h).max())\n",
        "ax.set_xlim(0, 10)\n",
        "ax.set_ylim(-50, np.ceil(peak / 5.0) * 5.0 + 5)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax.set_title('Zhu 2023 setup — W-band warm-rain Doppler spectrum')\n",
        "ax.legend(); ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Zoom on the large-drop tail\n",
       "\n",
       "Narrowing is most visible between v ≈ 7–9 m/s, where the fastest\n",
       "drops land. Zhu 2023's Lagrangian drop-tracking simulator produces\n",
       "the same qualitative signature (their Fig. 3–5).\n"),
    code(
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.plot(conv.v, dBZ(conv.sZ_h), 'C0-', label='conventional')\n",
        "ax.plot(iner.v, dBZ(iner.sZ_h), 'C3-', label='inertia-aware')\n",
        "ax.set_xlim(6, 10)\n",
        "tail_peak = max(dBZ(conv.sZ_h[(conv.v > 6) & (conv.v < 10)]).max(),\n",
        "                dBZ(iner.sZ_h[(iner.v > 6) & (iner.v < 10)]).max())\n",
        "ax.set_ylim(-25, np.ceil(tail_peak / 5.0) * 5.0 + 5)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax.set_title('Large-drop tail: inertia narrows the spectrum')\n",
        "ax.legend(); ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB10 = [
    md(
        "# Tutorial 10 — Supercooled liquid water vs. snow at cloud-radar frequencies\n",
        "\n",
        "Reference: Billault-Roux, A.-C., Georgakaki, P., Grazioli, J.,\n",
        "Romanens, G., Sotiropoulou, G., Phillips, V., Nenes, A., and Berne,\n",
        "A., 2023. *Distinct secondary ice production processes observed in\n",
        "radar Doppler spectra: insights from a case study*, Atmos. Chem.\n",
        "Phys., 23, 10207–10234 (doi:10.5194/acp-23-10207-2023).\n",
        "\n",
        "Mixed-phase cloud volumes contain supercooled liquid droplets (SLW)\n",
        "and ice particles side by side. The two populations have completely\n",
        "different scattering and fall-speed signatures:\n",
        "\n",
        "* **SLW**: small (≲200 µm), spherical, cold refractive index of\n",
        "  water, falls at a few cm/s. Rayleigh at both X- and W-band ⇒ very\n",
        "  low Z_h, Z_dr ≈ 0 dB, no polarimetric signature.\n",
        "* **Snow**: millimetre-scale oblate low-density aggregates, falls at\n",
        "  ~0.5–1 m/s. Moderately non-Rayleigh at W-band ⇒ higher Z_h, small\n",
        "  positive Z_dr from the habit anisotropy.\n",
        "\n",
        "This notebook builds dedicated scatterers for each population, shows\n",
        "their σ_b(D) and bulk radar observables at X and W band, and then\n",
        "combines them in a `HydroMix` to produce the bimodal Doppler spectrum\n",
        "that motivates the Billault-Roux et al. case-study analysis.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import (HydroMix, MixtureComponent, Scatterer,\n",
        "                         SpectralIntegrator, radar, spectra)\n",
        "from rustmatrix.psd import ExponentialPSD, GammaPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_0C, mi\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, geom_vert_back,\n",
        "                                      wl_X, wl_W)\n",
    ),
    md("## Build a supercooled-liquid-water scatterer\n",
       "\n",
       "Small spherical drops (D in 10–200 µm), refractive index at 0°C,\n",
       "log-normal-ish gamma PSD centred around 30 µm. We use mm units\n",
       "throughout to match `rustmatrix` conventions.\n"),
    code(
        "SLW_DMAX = 0.2  # mm\n",
        "\n",
        "def build_slw(wl):\n",
        "    s = Scatterer(wavelength=wl, m=m_w_0C[wl],\n",
        "                  Kw_sqr=K_w_sqr[wl], axis_ratio=1.0,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = SLW_DMAX\n",
        "    integ.num_points = 128\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    # Gamma PSD: D0 = 0.03 mm (30 µm), Nw = 1e11 m⁻³ mm⁻¹, μ = 4\n",
        "    s.psd = GammaPSD(D0=0.03, Nw=1e11, mu=4, D_max=SLW_DMAX)\n",
        "    return s\n",
        "\n",
        "slw_X = build_slw(wl_X)\n",
        "slw_W = build_slw(wl_W)\n",
    ),
    md("## Build a snow scatterer (low-density oblate aggregates)\n"),
    code(
        "SNOW_DMAX = 8.0\n",
        "RHO_SNOW = 0.2\n",
        "AXIS_SNOW = 0.6\n",
        "\n",
        "def build_snow(wl):\n",
        "    s = Scatterer(wavelength=wl, m=mi(wl, RHO_SNOW),\n",
        "                  Kw_sqr=K_w_sqr[wl], axis_ratio=AXIS_SNOW,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = SNOW_DMAX\n",
        "    integ.num_points = 256\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=5e3, Lambda=1.0, D_max=SNOW_DMAX)\n",
        "    return s\n",
        "\n",
        "snow_X = build_snow(wl_X)\n",
        "snow_W = build_snow(wl_W)\n",
    ),
    md("## σ_b(D) — Rayleigh vs. Mie across the two populations\n"),
    code(
        "def sigma_b(wl, D_mm, m, axis_ratio):\n",
        "    s = Scatterer(radius=D_mm/2, wavelength=wl, m=m,\n",
        "                  Kw_sqr=K_w_sqr[wl], axis_ratio=axis_ratio,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return radar.radar_xsect(s)\n",
        "\n",
        "D_slw = np.linspace(0.005, SLW_DMAX, 60)\n",
        "D_snow = np.linspace(0.1, SNOW_DMAX, 200)\n",
        "\n",
        "sb_slw_X = np.array([sigma_b(wl_X, d, m_w_0C[wl_X], 1.0) for d in D_slw])\n",
        "sb_slw_W = np.array([sigma_b(wl_W, d, m_w_0C[wl_W], 1.0) for d in D_slw])\n",
        "sb_snow_X = np.array([sigma_b(wl_X, d, mi(wl_X, RHO_SNOW), AXIS_SNOW)\n",
        "                       for d in D_snow])\n",
        "sb_snow_W = np.array([sigma_b(wl_W, d, mi(wl_W, RHO_SNOW), AXIS_SNOW)\n",
        "                       for d in D_snow])\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7.5, 4.5))\n",
        "ax.loglog(D_slw, sb_slw_X, 'C0-',  label='SLW, X-band')\n",
        "ax.loglog(D_slw, sb_slw_W, 'C0--', label='SLW, W-band')\n",
        "ax.loglog(D_snow, sb_snow_X, 'C3-',  label='snow, X-band')\n",
        "ax.loglog(D_snow, sb_snow_W, 'C3--', label='snow, W-band')\n",
        "ax.set_xlabel('diameter D [mm]')\n",
        "ax.set_ylabel(r'$\\sigma_b$ [mm²]')\n",
        "ax.set_title('Single-particle backscatter: SLW droplets vs. snow aggregates')\n",
        "ax.legend(fontsize=9); ax.grid(True, which='both', alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Bulk radar observables at X and W band\n",
       "\n",
       "Z_h(SLW) is ~40+ dB below Z_h(snow) even though the droplet\n",
       "concentration is high — the D⁶ Rayleigh penalty at 30-µm scale kills\n",
       "the signal. Z_dr is zero for SLW (spheres) but positive for snow\n",
       "(oblate). Dual-wavelength ratio DWR = Z_X − Z_W is near zero for SLW\n",
       "and positive for snow (non-Rayleigh at W-band).\n"),
    code(
        "def bulk(s):\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return 10 * np.log10(radar.refl(s))\n",
        "\n",
        "print(f'{\"\":<10} {\"Z_h X [dBZ]\":>12} {\"Z_h W [dBZ]\":>12} '\n",
        "      f'{\"DWR [dB]\":>10}')\n",
        "for name, sX, sW in [('SLW',  slw_X,  slw_W),\n",
        "                      ('snow', snow_X, snow_W)]:\n",
        "    zX = bulk(sX); zW = bulk(sW)\n",
        "    print(f'{name:<10} {zX:>12.2f} {zW:>12.2f} {zX - zW:>10.2f}')\n",
    ),
    md("## Bimodal Doppler spectrum of the SLW + snow mixture\n",
       "\n",
       "A `HydroMix` with per-component fall-speed and turbulence captures\n",
       "the two populations cleanly: SLW pins to v ≈ 0 with a narrow spread,\n",
       "snow sits near 0.5–1.0 m/s with a broader tail. Plotted in dBZ space\n",
       "the two modes are clearly separable even with realistic noise.\n"),
    code(
        "# Use W-band for the spectrum — best velocity-wise resolution of the\n",
        "# SLW mode, and non-Rayleigh snow signature is most evident here.\n",
        "mix = HydroMix([\n",
        "    MixtureComponent(slw_W,  slw_W.psd,  'slw'),\n",
        "    MixtureComponent(snow_W, snow_W.psd, 'snow'),\n",
        "])\n",
        "\n",
        "integ = SpectralIntegrator(\n",
        "    mix,\n",
        "    component_kinematics={\n",
        "        'slw':  (lambda D: 0.003 * (D / 0.01) ** 2,\n",
        "                 spectra.GaussianTurbulence(0.1)),\n",
        "        'snow': (spectra.fall_speed.locatelli_hobbs_1974_aggregates,\n",
        "                 spectra.GaussianTurbulence(0.2)),\n",
        "    },\n",
        "    v_min=-1.0, v_max=3.0, n_bins=1024,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        "    noise='realistic',\n",
        ").run()\n",
        "\n",
        "def dBZ(x):\n",
        "    return 10 * np.log10(np.maximum(x, 1e-12))\n",
        "\n",
        "# Run each population on its own (no noise) so each mode's true peak\n",
        "# is unambiguous. The HydroMix spectrum is dominated by snow (~50 dB\n",
        "# louder than SLW), so looking for the SLW peak on the combined,\n",
        "# noise-added spectrum would just pick up the snow tail crossing\n",
        "# through the near-zero velocity range.\n",
        "slw_only = SpectralIntegrator(\n",
        "    slw_W,\n",
        "    fall_speed=lambda D: 0.003 * (D / 0.01) ** 2,\n",
        "    turbulence=spectra.GaussianTurbulence(0.1),\n",
        "    v_min=-1.0, v_max=3.0, n_bins=1024,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        ").run()\n",
        "snow_only = SpectralIntegrator(\n",
        "    snow_W,\n",
        "    fall_speed=spectra.fall_speed.locatelli_hobbs_1974_aggregates,\n",
        "    turbulence=spectra.GaussianTurbulence(0.2),\n",
        "    v_min=-1.0, v_max=3.0, n_bins=1024,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        ").run()\n",
        "\n",
        "v_slw  = slw_only.v[int(np.argmax(slw_only.sZ_h))]\n",
        "v_snow = snow_only.v[int(np.argmax(snow_only.sZ_h))]\n",
        "print(f'SLW mode peak  v = {v_slw:+.3f} m/s')\n",
        "print(f'snow mode peak v = {v_snow:+.3f} m/s')\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.plot(slw_only.v, dBZ(slw_only.sZ_h), 'C2-', lw=1.3, label='SLW only')\n",
        "ax.plot(snow_only.v, dBZ(snow_only.sZ_h), 'C3-', lw=1.3, label='snow only')\n",
        "ax.plot(integ.v, dBZ(integ.sZ_h), 'C0-', lw=2.0,\n",
        "        label='SLW + snow (HydroMix, with noise)')\n",
        "ax.axvline(v_slw,  color='C2', alpha=0.4, ls=':',\n",
        "           label=f'SLW peak ({v_slw:+.2f})')\n",
        "ax.axvline(v_snow, color='C3', alpha=0.4, ls=':',\n",
        "           label=f'snow peak ({v_snow:+.2f})')\n",
        "ax.axhline(dBZ(integ.noise_h / (integ.v[-1] - integ.v[0])),\n",
        "           color='k', ls='--', alpha=0.5, label='noise floor')\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax.set_title('W-band SLW vs. snow vs. combined Doppler spectrum')\n",
        "ax.legend(fontsize=9, loc='upper right'); ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Takeaway\n",
       "\n",
       "The Billault-Roux et al. 2023 case study relies on the *spectral*\n",
       "separability demonstrated here: a narrow near-zero Doppler peak is\n",
       "SLW, a broader fall-velocity peak is ice; the polarimetric spectral\n",
       "variables further distinguish columnar (high SLDR) from planar and\n",
       "aggregated ice. With the two populations built as independent\n",
       "rustmatrix scatterers you can plug them into `HydroMix` and recover\n",
       "bulk radar observables that match what a vertically-pointing radar\n",
       "would measure, or analyse the spectral signatures by looking at the\n",
       "individual modes.\n"),
]


NB11 = [
    md(
        "# Tutorial 11 — Dual-frequency radar signatures across hydrometeor classes\n",
        "\n",
        "Reference: Honeyager, R., 2013. *Investigating the use of the T-matrix\n",
        "method as a proxy for the discrete dipole approximation*, M.S. thesis,\n",
        "Florida State University.\n",
        "\n",
        "Honeyager's thesis argues that the T-matrix applied to a size-matched\n",
        "spheroid, with a dielectric built from an ice / air mixing formula at\n",
        "the right *volume fraction*, reproduces the single-scattering\n",
        "properties of a geometrically-complex hydrometeor (bullet rosettes,\n",
        "plates, dendrites, aggregates) computed with DDA — provided the size\n",
        "parameter χ = 2π r / λ and the effective density are right.\n",
        "\n",
        "That framing is directly useful for dual-frequency radar work: the\n",
        "whole zoo of ice habits collapses, to first order, onto a\n",
        "two-parameter family (*effective density ρ_eff*, *axis ratio*) that\n",
        "`rustmatrix` already supports via `refractive.mi(wl, rho)` and the\n",
        "`axis_ratio` keyword. This notebook walks through four representative\n",
        "hydrometeor classes:\n",
        "\n",
        "| class                | ρ_eff [g/cm³] | axis ratio |\n",
        "|----------------------|---------------|------------|\n",
        "| rain                 | 1.00 (water)  | Thurai 2007|\n",
        "| low-density aggregate| 0.10          | 0.70       |\n",
        "| graupel              | 0.50          | 0.90       |\n",
        "| high-density ice     | 0.90          | 1.00       |\n",
        "\n",
        "and shows how each class signs itself into single-particle σ_b(D),\n",
        "bulk DWR vs. D₀, and the spectral DWR profile sDWR(v).\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, SpectralIntegrator, radar, spectra\n",
        "from rustmatrix.psd import ExponentialPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_10C, mi\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, dsr_thurai_2007,\n",
        "                                      geom_vert_back, wl_X, wl_W)\n",
        "\n",
        "CLASSES = {\n",
        "    'rain':     dict(rho=1.00, axis_ratio=None),   # Thurai below\n",
        "    'low-ρ agg':dict(rho=0.10, axis_ratio=0.70),\n",
        "    'graupel':  dict(rho=0.50, axis_ratio=0.90),\n",
        "    'high-ρ ice':dict(rho=0.90, axis_ratio=1.00),\n",
        "}\n",
        "\n",
        "def refractive_index(wl, cls):\n",
        "    return m_w_10C[wl] if cls == 'rain' else mi(wl, CLASSES[cls]['rho'])\n",
        "\n",
        "def class_axis_ratio(cls, D_mm):\n",
        "    ar = CLASSES[cls]['axis_ratio']\n",
        "    return (1.0 / dsr_thurai_2007(D_mm)) if ar is None else ar\n",
        "\n",
        "COLORS = {'rain': 'C0', 'low-ρ agg': 'C2',\n",
        "          'graupel': 'C1', 'high-ρ ice': 'C3'}\n",
    ),
    md("## Single-particle σ_b(D) at X and W\n",
       "\n",
       "For each class, tabulate the single-particle backscatter cross-section\n",
       "at vertical incidence across 0.2–8 mm equivalent diameter. The key\n",
       "effects to watch:\n",
       "\n",
       "* **Rayleigh regime** — all classes follow σ_b ∝ D⁶ at small D, but\n",
       "  offset vertically by |K(ρ)|² differences. Low-ρ ice sits ~30 dB below\n",
       "  water at equal D.\n",
       "* **Non-Rayleigh onset at W-band** — the first Mie minimum appears once\n",
       "  χ = πD/λ ≈ 1, i.e. D ≈ 1 mm at W-band. That happens for all four\n",
       "  classes because χ is set by size, not ρ.\n",
       "* **Mie oscillation amplitude** — *this* is where ρ matters. Denser\n",
       "  classes (rain, high-ρ ice) show sharp Mie minima/maxima; low-density\n",
       "  aggregates barely oscillate because their refractive index contrast\n",
       "  with air is small.\n"),
    code(
        "def sigma_b(wl, cls, D_mm):\n",
        "    s = Scatterer(radius=D_mm/2, wavelength=wl,\n",
        "                  m=refractive_index(wl, cls),\n",
        "                  Kw_sqr=K_w_sqr[wl],\n",
        "                  axis_ratio=class_axis_ratio(cls, D_mm),\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return radar.radar_xsect(s)\n",
        "\n",
        "D_grid = np.linspace(0.2, 8.0, 100)\n",
        "sigma = {cls: {b: np.array([sigma_b(wl, cls, D) for D in D_grid])\n",
        "               for b, wl in [('X', wl_X), ('W', wl_W)]}\n",
        "         for cls in CLASSES}\n",
        "\n",
        "fig, (axX, axW) = plt.subplots(1, 2, figsize=(11, 4), sharey=True)\n",
        "for cls in CLASSES:\n",
        "    axX.loglog(D_grid, sigma[cls]['X'], color=COLORS[cls], label=cls)\n",
        "    axW.loglog(D_grid, sigma[cls]['W'], color=COLORS[cls], label=cls)\n",
        "axX.set_title('σ_b(D) at X-band (9 GHz)')\n",
        "axW.set_title('σ_b(D) at W-band (94 GHz)')\n",
        "for ax in (axX, axW):\n",
        "    ax.set_xlabel('D [mm]')\n",
        "    ax.grid(True, which='both', alpha=0.3)\n",
        "    ax.legend(fontsize=9)\n",
        "axX.set_ylabel(r'$\\sigma_b$ [mm²]')\n",
        "fig.tight_layout();\n",
    ),
    md("## DWR(D) — single-particle dual-wavelength ratio\n",
       "\n",
       "Re-plotting as DWR(D) = 10·log₁₀(σ_b^X / σ_b^W) collapses the key\n",
       "information: the *size where each class first walks out of Rayleigh*.\n",
       "This is Honeyager's thesis Table 2.2 idea generalised to arbitrary\n",
       "habit — the χ parameter that sets Rayleigh validity is hidden inside\n",
       "ρ_eff via the refractive index contrast.\n"),
    code(
        "# Equivalent reflectivity normalisation: Ze = λ⁴ / (π⁵ |K_w|²) · σ_b.\n",
        "# In the Rayleigh regime Ze_X = Ze_W, so DWR_{X-W} = 0 dB; any positive\n",
        "# excursion is a direct signature of non-Rayleigh scattering at W-band.\n",
        "def single_Ze(sig, wl, Kw2):\n",
        "    return wl**4 / (np.pi**5 * Kw2) * sig\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4.5))\n",
        "dwr_curves_1p = {}\n",
        "for cls in CLASSES:\n",
        "    zeX = single_Ze(sigma[cls]['X'], wl_X, K_w_sqr[wl_X])\n",
        "    zeW = single_Ze(sigma[cls]['W'], wl_W, K_w_sqr[wl_W])\n",
        "    dwr = 10 * np.log10(zeX / zeW)\n",
        "    dwr_curves_1p[cls] = dwr\n",
        "    ax.plot(D_grid, dwr, color=COLORS[cls], lw=1.8, label=cls)\n",
        "ax.axhline(0.0, color='k', ls=':', alpha=0.5, label='Rayleigh (DWR=0)')\n",
        "ax.set_xlabel('diameter D [mm]')\n",
        "ax.set_ylabel('single-particle DWR$_{X-W}$ [dB]')\n",
        "ax.set_title('Where does each habit walk out of Rayleigh?')\n",
        "ax.set_xlim(0, 8); ax.grid(True, alpha=0.3); ax.legend(fontsize=9)\n",
        "fig.tight_layout();\n",
        "\n",
        "print('Approximate D at which single-particle DWR crosses +3 dB:')\n",
        "for cls, dwr in dwr_curves_1p.items():\n",
        "    above = np.where(dwr > 3.0)[0]\n",
        "    label = f'{D_grid[above[0]]:.2f} mm' if len(above) else '> 8 mm (stays Rayleigh)'\n",
        "    print(f'  {cls:<12}  {label}')\n",
    ),
    md("## Bulk DWR vs. median-volume diameter D₀\n",
       "\n",
       "The single-particle curves fold through a PSD in the bulk radar\n",
       "measurement. Hold the habit fixed, sweep the exponential PSD slope Λ\n",
       "(so D₀ = 3.67/Λ varies), and plot the resulting bulk DWR. The curve\n",
       "tells you how sensitive each habit's dual-frequency signature is to\n",
       "the *population-average* particle size.\n"),
    code(
        "def bulk_Zh(wl, cls, N0, lam, Dmax):\n",
        "    s = Scatterer(wavelength=wl, m=refractive_index(wl, cls),\n",
        "                  Kw_sqr=K_w_sqr[wl], ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = Dmax; integ.num_points = 128\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    if CLASSES[cls]['axis_ratio'] is None:\n",
        "        integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    else:\n",
        "        s.axis_ratio = CLASSES[cls]['axis_ratio']\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=N0, Lambda=lam, D_max=Dmax)\n",
        "    s.set_geometry(geom_vert_back)\n",
        "    return radar.refl(s)\n",
        "\n",
        "# Hold N0 fixed, sweep Λ so D0 = 3.67/Λ spans 0.4–3 mm\n",
        "Lambdas = np.linspace(1.2, 9.0, 10)   # mm⁻¹\n",
        "D0s = 3.67 / Lambdas\n",
        "DMAX = 8.0; N0 = 8e3\n",
        "\n",
        "dwr_curves = {}\n",
        "for cls in CLASSES:\n",
        "    dwr = []\n",
        "    for lam in Lambdas:\n",
        "        zX = bulk_Zh(wl_X, cls, N0, lam, DMAX)\n",
        "        zW = bulk_Zh(wl_W, cls, N0, lam, DMAX)\n",
        "        dwr.append(10 * np.log10(zX / zW))\n",
        "    dwr_curves[cls] = np.asarray(dwr)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4.5))\n",
        "for cls, d in dwr_curves.items():\n",
        "    ax.plot(D0s, d, color=COLORS[cls], lw=1.8, marker='o',\n",
        "            markersize=4, label=cls)\n",
        "ax.axhline(0.0, color='k', ls=':', alpha=0.5)\n",
        "ax.set_xlabel('median-volume diameter $D_0$ [mm]')\n",
        "ax.set_ylabel('bulk DWR$_{X-W}$ [dB]')\n",
        "ax.set_title('Bulk DWR vs. PSD size — one line per hydrometeor class')\n",
        "ax.grid(True, alpha=0.3); ax.legend(fontsize=9)\n",
        "fig.tight_layout();\n",
    ),
    md("## Dual-frequency Doppler spectra — aggregate vs. graupel\n",
       "\n",
       "Now pull the spectral version together. Two bulk populations that\n",
       "*can't* be told apart by reflectivity alone — a low-density aggregate\n",
       "PSD and a graupel PSD tuned to give the same X-band Z_h — show very\n",
       "different sDWR(v) profiles. Aggregates have a mostly-monotonic rise\n",
       "because their σ_b(D) curve stays smooth; graupel's spectrum carries\n",
       "the Mie-resonance structure of its single-particle σ_b(D) through into\n",
       "velocity space, since every drop size maps deterministically to its\n",
       "own fall speed.\n"),
    code(
        "def build(cls, N0, lam, Dmax, wl):\n",
        "    s = Scatterer(wavelength=wl, m=refractive_index(wl, cls),\n",
        "                  Kw_sqr=K_w_sqr[wl], ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = Dmax; integ.num_points = 256\n",
        "    integ.geometries = (geom_vert_back,)\n",
        "    if CLASSES[cls]['axis_ratio'] is None:\n",
        "        integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    else:\n",
        "        s.axis_ratio = CLASSES[cls]['axis_ratio']\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=N0, Lambda=lam, D_max=Dmax)\n",
        "    return s\n",
        "\n",
        "# PSDs chosen so both give ~moderate snowfall X-band reflectivity.\n",
        "# Aggregate: low density, broader PSD to Dmax=6 mm.\n",
        "# Graupel:   medium density, narrower PSD (smaller max D).\n",
        "agg_X = build('low-ρ agg', N0=2e4, lam=2.0, Dmax=6.0, wl=wl_X)\n",
        "agg_W = build('low-ρ agg', N0=2e4, lam=2.0, Dmax=6.0, wl=wl_W)\n",
        "gra_X = build('graupel',   N0=5e3, lam=3.0, Dmax=4.0, wl=wl_X)\n",
        "gra_W = build('graupel',   N0=5e3, lam=3.0, Dmax=4.0, wl=wl_W)\n",
        "\n",
        "fall_agg = spectra.fall_speed.locatelli_hobbs_1974_aggregates\n",
        "fall_gra = spectra.fall_speed.locatelli_hobbs_1974_graupel_hex\n",
        "turb = spectra.GaussianTurbulence(0.2)\n",
        "V_MIN, V_MAX = -0.5, 4.0\n",
        "\n",
        "def run(sc, fall):\n",
        "    return SpectralIntegrator(\n",
        "        sc, fall_speed=fall, turbulence=turb,\n",
        "        v_min=V_MIN, v_max=V_MAX, n_bins=1024,\n",
        "        geometry_backscatter=geom_vert_back,\n",
        "    ).run()\n",
        "\n",
        "r_agg_X = run(agg_X, fall_agg); r_agg_W = run(agg_W, fall_agg)\n",
        "r_gra_X = run(gra_X, fall_gra); r_gra_W = run(gra_W, fall_gra)\n",
        "\n",
        "def dBZ(x):\n",
        "    return 10 * np.log10(np.maximum(x, 1e-12))\n",
        "\n",
        "print(f'{\"population\":<15} {\"Z_h X [dBZ]\":>12} {\"Z_h W [dBZ]\":>12} '\n",
        "      f'{\"DWR [dB]\":>10}')\n",
        "for name, rX, rW in [('low-ρ agg', r_agg_X, r_agg_W),\n",
        "                      ('graupel',   r_gra_X, r_gra_W)]:\n",
        "    zX = 10 * np.log10(np.trapezoid(rX.sZ_h, rX.v))\n",
        "    zW = 10 * np.log10(np.trapezoid(rW.sZ_h, rW.v))\n",
        "    print(f'{name:<15} {zX:>12.2f} {zW:>12.2f} {zX - zW:>10.2f}')\n",
        "\n",
        "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6.5), sharex=True)\n",
        "ax1.plot(r_agg_X.v, dBZ(r_agg_X.sZ_h), 'C2-', label='agg, X-band')\n",
        "ax1.plot(r_agg_W.v, dBZ(r_agg_W.sZ_h), 'C2--', label='agg, W-band')\n",
        "ax1.plot(r_gra_X.v, dBZ(r_gra_X.sZ_h), 'C1-', label='graupel, X-band')\n",
        "ax1.plot(r_gra_W.v, dBZ(r_gra_W.sZ_h), 'C1--', label='graupel, W-band')\n",
        "ax1.set_ylabel('sZ_h [dBZ / (m/s)]')\n",
        "ax1.set_title('Dual-frequency Doppler spectra')\n",
        "ax1.legend(fontsize=9); ax1.grid(True, alpha=0.3)\n",
        "\n",
        "sdwr_agg = dBZ(r_agg_X.sZ_h) - dBZ(r_agg_W.sZ_h)\n",
        "sdwr_gra = dBZ(r_gra_X.sZ_h) - dBZ(r_gra_W.sZ_h)\n",
        "mask_agg = (r_agg_X.sZ_h > 1e-8) & (r_agg_W.sZ_h > 1e-10)\n",
        "mask_gra = (r_gra_X.sZ_h > 1e-8) & (r_gra_W.sZ_h > 1e-10)\n",
        "ax2.plot(r_agg_X.v[mask_agg], sdwr_agg[mask_agg], 'C2-',\n",
        "         lw=1.6, label='low-ρ agg')\n",
        "ax2.plot(r_gra_X.v[mask_gra], sdwr_gra[mask_gra], 'C1-',\n",
        "         lw=1.6, label='graupel')\n",
        "ax2.axhline(0.0, color='k', ls=':', alpha=0.5)\n",
        "ax2.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax2.set_ylabel('sDWR$_{X-W}$ [dB]')\n",
        "ax2.set_title('Spectral DWR — aggregates smooth, graupel resonant')\n",
        "ax2.set_xlim(V_MIN, V_MAX)\n",
        "ax2.legend(fontsize=9); ax2.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
    md("## Takeaway\n",
       "\n",
       "Following Honeyager 2013's framing, we've used a single T-matrix\n",
       "spheroid code path with four choices of (ρ_eff, axis ratio) to span\n",
       "four physically distinct hydrometeor classes. Two observations pop\n",
       "out that matter for interpreting dual-frequency radar data:\n",
       "\n",
       "* **The *size* at which DWR departs from zero is set by χ = πD/λ**\n",
       "  (≈ 1 mm at W-band), not by ρ_eff. But **the amplitude and shape**\n",
       "  of the DWR(D) curve beyond that threshold is a direct fingerprint\n",
       "  of ρ_eff: dense classes oscillate strongly, low-ρ aggregates rise\n",
       "  smoothly and slowly.\n",
       "* **Bulk DWR sweeps out very different trajectories with D₀**, so a\n",
       "  single (Z_h, DWR) measurement can be mapped to a habit-dependent\n",
       "  D₀ estimate provided you commit to a class — this is exactly the\n",
       "  lookup-table strategy that papers like Mason et al. 2019 and\n",
       "  Tridon et al. 2019 build their retrievals on.\n",
       "* **Spectral DWR resolves habit ambiguity** that bulk DWR can't:\n",
       "  graupel's Mie resonances appear as wiggles in sDWR(v), while\n",
       "  low-ρ aggregates produce a smooth monotonic rise.\n",
       "\n",
       "Swapping (ρ_eff, axis_ratio) for any other habit class (dendrites,\n",
       "rimed aggregates, hail) is one `CLASSES` dict entry away.\n"),
]


def main() -> None:
    here = Path(__file__).parent
    for name, cells in (("01_sphere_mie.ipynb", NB01),
                        ("02_raindrop_zdr.ipynb", NB02),
                        ("03_psd_gamma_rain.ipynb", NB03),
                        ("04_oriented_ice.ipynb", NB04),
                        ("05_radar_band_sweep.ipynb", NB05),
                        ("06_hd_mix.ipynb", NB06),
                        ("07_doppler_spectrum_rain.ipynb", NB07),
                        ("08_spectral_polarimetry_rain_ice.ipynb", NB08),
                        ("09_zhu_2023_particle_inertia.ipynb", NB09),
                        ("10_slw_vs_snow.ipynb", NB10),
                        ("11_honeyager_hydrometeor_classes.ipynb", NB11)):
        path = here / name
        with open(path, "w") as f:
            json.dump(notebook(cells), f, indent=1)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
